### ISSUE TITLE
Create instance for Indiana UP

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold-pilot-program#1]
Host: IUP
Domain: `https://publish.iupress.indiana.edu/`
Colors: Crimson: #990000; Cream: #EDEBEB
Logo: [Available here](https://user-images.githubusercontent.com/25825222/44877262-09289c00-ac69-11e8-931f-114246bcf6eb.jpg)

**Comment by tsmyre** [comment]
Update: Indiana will be installing on their own, reaching out when/if necessary.

**Comment by tsmyre** [comment]
Indiana got their instance up and running on 13 Sept.

**Comment by rclarkburns** [comment]
Sorry. Thought I missed one but read through the comments just now! 👍
