### ISSUE TITLE
Setup Google Drive integration

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold-pilot-program#10]
For those pilots being hosted by MDS, let's setup Google Drive integration. Those with active domains are:

- https://liverpooluniversitypress.manifoldapp.org/
- https://ucincinnatipress.manifoldapp.org/
- https://concordia.manifoldapp.org/
- https://aupress.manifoldapp.org/
- https://temple.manifoldapp.org/
- https://uwipress.manifoldapp.org/
- https://uw.manifoldapp.org/
- https://umnlibraries.manifoldapp.org/

**Comment by zdavis** [comment]
Done.
