### ISSUE TITLE
Create Instance for Reanimate Publishing

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold-pilot-program#11]
Host: MDS
Domain: `http://reanimatepublishing.manifoldapp.org/`
Colors: Navy Blue: #031C35; Light Blue: #2ADAFE
Logo: [Available Here](https://user-images.githubusercontent.com/25825222/45960873-ce552200-bfe2-11e8-8b4f-93f5f475246b.png)

**Comment by rclarkburns** [comment]
@tsmyre @zdavis This is complete. Admin accounts have been created using the standard temporary password.
