### ISSUE TITLE
Create Instance for Emory

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold-pilot-program#12]
Host: MDS
Domain: `http://manifold.ecds.emory.edu/`
Colors: Blue: #002878; Gray: #BDBfC1
Logos: [Desktop](https://user-images.githubusercontent.com/25825222/46174492-d0cbac00-c26e-11e8-887e-dade174dec7a.png) and [Mobile](https://user-images.githubusercontent.com/25825222/46174509-dcb76e00-c26e-11e8-8825-61622e11590d.png)

Our primary contact, Yang Li, notes,

> Our system team will obtain certs for this domain and if there is anything that the Manifold engineering team would like to know, please don’t hesitate to reach out.

Yang is in our Slack channel.

**Comment by rclarkburns** [comment]
@zdavis Went as far as I could without the DNS record. Once the record is added, puppet needs to be run on the host then the emory deployment can be kicked off and admin setup completed.

**Comment by rclarkburns** [comment]
@tsmyre @zdavis Instance and configuration has been completed: https://manifold.ecds.emory.edu I created admin accounts for both of you using the standard credentials. Let me know if you need anything else on this. Thanks!
