### ISSUE TITLE
Create Instance for Lapham’s Quarterly

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold-pilot-program#18]
Host: MDS
Domain: https://laphamsquarterly.manifoldapp.org/
Base Color: #CDAC77
Logo: [On Drive](https://drive.google.com/file/d/1NB2Z71r6sLHWZMA1xQMlJbCFO7yFSFyV/view?usp=sharing)
Favicon: [On Drive](https://drive.google.com/file/d/19WZQZHGEYx79PKzYcuPqTkIefz_U5UzX/view?usp=sharing)
Note: LQ will create a CNAME record in their domain's DNS that points to `https://laphamsquarterly.manifoldapp.org/` from `https://annotated.laphamsquarterly.org`.

**Comment by zdavis** [comment]
Note to self: look at CNAME.
