### ISSUE TITLE
Create Instance for Concordia University Press

### ISSUE THREAD

**Issue by tsmyre** [ManifoldScholar/manifold-pilot-program#9]
Host: MDS
Domain: `https://concordia.manifoldapp.org/`
Colors: Red: #932439; Gray: #4B4B4B
Logo: [Available Here](https://user-images.githubusercontent.com/25825222/45845904-fc3d1c80-bceb-11e8-9c48-7580e6cf9628.jpg)

**Comment by rclarkburns** [comment]
@tsmyre @zdavis This is complete. Admin accounts have been created using the standard temporary password.
